name: docker

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build with docker-compose
        run: docker-compose build

      - name: Tag image
        run: docker tag appjava ${USERNAME}/appjava:latest

      - name: Push image to Docker Hub
        run: docker push ${USERNAME}/appjava:latest