name: Build l'application
on:
  push:
    branches:
      - main

jobs:
  recuperation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Get Code
        uses: actions/checkout@v3
      - name: Dependencies installation
        run: mvn install -DskipTests
      - name: Build app
        run: mvn package
