name: Build l'application
on:
  push:
    branches:
      - main

jobs:
  recuperation:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Get Code
        uses: actions/checkout@v3
      - name: Dependencies installation
        run: mvn install -DskipTests
      - name: Build app
        run: mvn package -DskipTests
        
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Upload artifact
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: build_app
          path: target/*.jar
