name: Réponse automatique à une issue
on:
    issues:
        types: opened
jobs:
    reply:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: Répondre à une issue
              env:
                ISSUE_URL: ${{github.event.issue.html_url}}
                ISSUE_AUTHOR: ${{github.event.issue.user.login}}
                ISSUE_NAME: ${{github.event.issue.title}}
              run: | 
                gh issue comment $ISSUE_URL --body "Bonjour $ISSUE_AUTHOR, nous avons bien pris en compte votre problème du nom de : $ISSUE_NAME"